version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: portal-mamaloo_frontend:prod
    container_name: prodFrontend-portalMamaloo
    environment:
      NODE_ENV: production
      VITE_API_URL: https://api.seudominio.com
    restart: always
    networks:
      - mamaloo_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: portal-mamaloo_backend:prod
    container_name: prodBackend-portalMamaloo
    env_file:
      - .env.production
    volumes:
      - ./uploads:/app/uploads
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      SECRET_KEY: ${SECRET_KEY}
      ENVIRONMENT: production
      DEBUG: "false"
    restart: always
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mamaloo_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8025/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  database:
    image: postgres:15-alpine
    container_name: database-portalMamaloo
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: meubanco
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    restart: always
    networks:
      - mamaloo_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meubanco"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: portal-mamaloo_nginx:prod
    container_name: nginx-portalMamaloo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./uploads:/usr/share/nginx/html/uploads:ro
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - mamaloo_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pg_data_prod:

networks:
  mamaloo_net:
    driver: bridge