apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mamaloo-app.fullname" . }}-db-secret
  labels:
    {{- include "mamaloo-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRES_DB: {{ .Values.database.database | quote }}
  DATABASE_URL: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ include "mamaloo-app.fullname" . }}-database:{{ .Values.database.port }}/{{ .Values.database.database }}"
