{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mamaloo-app.fullname" . }}-database
  labels:
    {{- include "mamaloo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.database.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "mamaloo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
